<?php

namespace Database\Seeders;

use App\Models\UrbanGoodzLoadBoardLoad;
use Illuminate\Database\Seeder;

class UrbanGoodzLoadBoardSeeder extends Seeder
{
    public function run(): void
    {
        if (UrbanGoodzLoadBoardLoad::count() > 0) {
            return;
        }

        $loads = [
            [
                'load_number' => 'LB-2026-0001',
                'origin_name' => 'Walmart Distribution Center',
                'origin_city' => 'Houston', 'origin_state' => 'TX', 'origin_zip' => '77001',
                'origin_lat' => 29.7604, 'origin_lng' => -95.3698,
                'destination_name' => 'Target Distribution Center',
                'destination_city' => 'Dallas', 'destination_state' => 'TX', 'destination_zip' => '75201',
                'destination_lat' => 32.7767, 'destination_lng' => -96.7970,
                'distance_miles' => 239, 'estimated_duration_minutes' => 210,
                'payout_amount' => 850.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.56,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 38000, 'length_ft' => 53, 'pieces' => 24,
                'commodity_description' => 'General merchandise - retail goods',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Marcus Johnson', 'shipper_phone' => '713-555-0101',
                'consignee_name' => 'Angela Torres', 'consignee_phone' => '214-555-0202',
            ],
            [
                'load_number' => 'LB-2026-0002',
                'origin_name' => 'Sysco Foods',
                'origin_city' => 'San Antonio', 'origin_state' => 'TX', 'origin_zip' => '78201',
                'origin_lat' => 29.4241, 'origin_lng' => -98.4936,
                'destination_name' => 'US Foods',
                'destination_city' => 'Austin', 'destination_state' => 'TX', 'destination_zip' => '73301',
                'destination_lat' => 30.2672, 'destination_lng' => -97.7431,
                'distance_miles' => 80, 'estimated_duration_minutes' => 75,
                'payout_amount' => 425.00, 'payout_type' => 'flat', 'rate_per_mile' => 5.31,
                'load_type' => 'ftl', 'equipment_type' => 'reefer', 'weight_lbs' => 28000, 'length_ft' => 48, 'pieces' => 16,
                'commodity_description' => 'Frozen foods - temperature sensitive',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => -10, 'temperature_max_f' => 0,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Derrick Williams', 'shipper_phone' => '210-555-0303',
                'consignee_name' => 'Patricia Nguyen', 'consignee_phone' => '512-555-0404',
            ],
            [
                'load_number' => 'LB-2026-0003',
                'origin_name' => 'ExxonMobil Refinery',
                'origin_city' => 'Baytown', 'origin_state' => 'TX', 'origin_zip' => '77520',
                'origin_lat' => 29.7508, 'origin_lng' => -94.9774,
                'destination_name' => 'Dow Chemical',
                'destination_city' => 'Lake Charles', 'destination_state' => 'LA', 'destination_zip' => '70601',
                'destination_lat' => 30.2266, 'destination_lng' => -93.2174,
                'distance_miles' => 145, 'estimated_duration_minutes' => 135,
                'payout_amount' => 675.00, 'payout_type' => 'flat', 'rate_per_mile' => 4.66,
                'load_type' => 'ftl', 'equipment_type' => 'tanker', 'weight_lbs' => 45000,
                'commodity_description' => 'Industrial chemicals - non-hazardous lubricants',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Robert Chen', 'shipper_phone' => '281-555-0505',
                'consignee_name' => 'Lisa Broussard', 'consignee_phone' => '337-555-0606',
            ],
            [
                'load_number' => 'LB-2026-0004',
                'origin_name' => 'Home Depot RDC',
                'origin_city' => 'Memphis', 'origin_state' => 'TN', 'origin_zip' => '38101',
                'origin_lat' => 35.1495, 'origin_lng' => -90.0490,
                'destination_name' => 'Lowe\'s Distribution',
                'destination_city' => 'Nashville', 'destination_state' => 'TN', 'destination_zip' => '37201',
                'destination_lat' => 36.1627, 'destination_lng' => -86.7816,
                'distance_miles' => 210, 'estimated_duration_minutes' => 195,
                'payout_amount' => 780.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.71,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 42000, 'length_ft' => 53, 'pieces' => 30,
                'commodity_description' => 'Building materials and hardware',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'James Patterson', 'shipper_phone' => '901-555-0707',
                'consignee_name' => 'Sandra Mitchell', 'consignee_phone' => '615-555-0808',
            ],
            [
                'load_number' => 'LB-2026-0005',
                'origin_name' => 'Amazon Fulfillment Center',
                'origin_city' => 'Joliet', 'origin_state' => 'IL', 'origin_zip' => '60433',
                'origin_lat' => 41.5277, 'origin_lng' => -88.0825,
                'destination_name' => 'Amazon Sort Center',
                'destination_city' => 'Indianapolis', 'destination_state' => 'IN', 'destination_zip' => '46201',
                'destination_lat' => 39.7684, 'destination_lng' => -86.1581,
                'distance_miles' => 182, 'estimated_duration_minutes' => 165,
                'payout_amount' => 720.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.96,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 35000, 'length_ft' => 53, 'pieces' => 40,
                'commodity_description' => 'E-commerce parcels - mixed consumer goods',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Kevin Park', 'shipper_phone' => '815-555-0909',
                'consignee_name' => 'Maria Rodriguez', 'consignee_phone' => '317-555-1010',
            ],
            [
                'load_number' => 'LB-2026-0006',
                'origin_name' => 'Kroger Distribution',
                'origin_city' => 'Atlanta', 'origin_state' => 'GA', 'origin_zip' => '30301',
                'origin_lat' => 33.7490, 'origin_lng' => -84.3880,
                'destination_name' => 'Kroger Marketplace',
                'destination_city' => 'Charlotte', 'destination_state' => 'NC', 'destination_zip' => '28201',
                'destination_lat' => 35.2271, 'destination_lng' => -80.8431,
                'distance_miles' => 245, 'estimated_duration_minutes' => 225,
                'payout_amount' => 920.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.76,
                'load_type' => 'ftl', 'equipment_type' => 'reefer', 'weight_lbs' => 40000, 'length_ft' => 53, 'pieces' => 28,
                'commodity_description' => 'Grocery products - refrigerated dairy and produce',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => 33, 'temperature_max_f' => 38,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Tyrone Jackson', 'shipper_phone' => '404-555-1111',
                'consignee_name' => 'Kimberly White', 'consignee_phone' => '704-555-1212',
            ],
            [
                'load_number' => 'LB-2026-0007',
                'origin_name' => 'FedEx Ground Hub',
                'origin_city' => 'Memphis', 'origin_state' => 'TN', 'origin_zip' => '38118',
                'origin_lat' => 35.0353, 'origin_lng' => -89.9767,
                'destination_name' => 'FedEx Station',
                'destination_city' => 'Little Rock', 'destination_state' => 'AR', 'destination_zip' => '72201',
                'destination_lat' => 34.7465, 'destination_lng' => -92.2896,
                'distance_miles' => 135, 'estimated_duration_minutes' => 120,
                'payout_amount' => 550.00, 'payout_type' => 'flat', 'rate_per_mile' => 4.07,
                'load_type' => 'ltl', 'equipment_type' => 'van', 'weight_lbs' => 15000, 'length_ft' => 48, 'pieces' => 20,
                'commodity_description' => 'Parcel sort - mixed packages',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Donna Evans', 'shipper_phone' => '901-555-1313',
                'consignee_name' => 'William Harris', 'consignee_phone' => '501-555-1414',
            ],
            [
                'load_number' => 'LB-2026-0008',
                'origin_name' => 'Plains All American Pipeline',
                'origin_city' => 'Midland', 'origin_state' => 'TX', 'origin_zip' => '79701',
                'origin_lat' => 31.9973, 'origin_lng' => -102.0779,
                'destination_name' => 'Enterprise Products',
                'destination_city' => 'Houston', 'destination_state' => 'TX', 'origin_zip' => '77002',
                'destination_lat' => 29.7545, 'destination_lng' => -95.3535,
                'distance_miles' => 435, 'estimated_duration_minutes' => 390,
                'payout_amount' => 1450.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.33,
                'load_type' => 'ftl', 'equipment_type' => 'tanker', 'weight_lbs' => 48000,
                'commodity_description' => 'Crude oil derivatives - pipeline transfer support',
                'is_hazmat' => true, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'George Martinez', 'shipper_phone' => '432-555-1515',
                'consignee_name' => 'Nancy Thompson', 'consignee_phone' => '713-555-1616',
            ],
            [
                'load_number' => 'LB-2026-0009',
                'origin_name' => 'Costco Wholesale',
                'origin_city' => 'Phoenix', 'origin_state' => 'AZ', 'origin_zip' => '85001',
                'origin_lat' => 33.4484, 'origin_lng' => -112.0740,
                'destination_name' => 'Costco Depot',
                'destination_city' => 'Las Vegas', 'destination_state' => 'NV', 'destination_zip' => '89101',
                'destination_lat' => 36.1699, 'destination_lng' => -115.1398,
                'distance_miles' => 275, 'estimated_duration_minutes' => 255,
                'payout_amount' => 980.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.56,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 44000, 'length_ft' => 53, 'pieces' => 36,
                'commodity_description' => 'Wholesale merchandise - palletized retail goods',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Carmen Delgado', 'shipper_phone' => '602-555-1717',
                'consignee_name' => 'Howard Kim', 'consignee_phone' => '702-555-1818',
            ],
            [
                'load_number' => 'LB-2026-0010',
                'origin_name' => 'DHL eCommerce',
                'origin_city' => 'Columbus', 'origin_state' => 'OH', 'origin_zip' => '43215',
                'origin_lat' => 39.9612, 'origin_lng' => -82.9988,
                'destination_name' => 'DHL Service Point',
                'destination_city' => 'Detroit', 'destination_state' => 'MI', 'destination_zip' => '48201',
                'destination_lat' => 42.3314, 'destination_lng' => -83.0458,
                'distance_miles' => 168, 'estimated_duration_minutes' => 150,
                'payout_amount' => 620.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.69,
                'load_type' => 'ltl', 'equipment_type' => 'van', 'weight_lbs' => 12000, 'length_ft' => 48, 'pieces' => 18,
                'commodity_description' => 'E-commerce parcels - last mile sort',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Raymond Brooks', 'shipper_phone' => '614-555-1919',
                'consignee_name' => 'Crystal Adams', 'consignee_phone' => '313-555-2020',
            ],
            [
                'load_number' => 'LB-2026-0011',
                'origin_name' => 'USPS PDC',
                'origin_city' => 'San Francisco', 'origin_state' => 'CA', 'origin_zip' => '94102',
                'origin_lat' => 37.7749, 'origin_lng' => -122.4194,
                'destination_name' => 'USPS Network Hub',
                'destination_city' => 'Sacramento', 'destination_state' => 'CA', 'destination_zip' => '95814',
                'destination_lat' => 38.5816, 'destination_lng' => -121.4944,
                'distance_miles' => 88, 'estimated_duration_minutes' => 80,
                'payout_amount' => 380.00, 'payout_type' => 'flat', 'rate_per_mile' => 4.32,
                'load_type' => 'ltl', 'equipment_type' => 'van', 'weight_lbs' => 8000, 'pieces' => 12,
                'commodity_description' => 'Priority mail containers',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Yolanda Sanchez', 'shipper_phone' => '415-555-2121',
                'consignee_name' => 'Timothy Clark', 'consignee_phone' => '916-555-2222',
            ],
            [
                'load_number' => 'LB-2026-0012',
                'origin_name' => 'PepsiCo Bottling',
                'origin_city' => 'Dallas', 'origin_state' => 'TX', 'origin_zip' => '75202',
                'origin_lat' => 32.7876, 'origin_lng' => -96.7985,
                'destination_name' => 'Frito-Lay Plant',
                'destination_city' => 'Waco', 'destination_state' => 'TX', 'destination_zip' => '76701',
                'destination_lat' => 31.5493, 'destination_lng' => -97.1467,
                'distance_miles' => 95, 'estimated_duration_minutes' => 85,
                'payout_amount' => 410.00, 'payout_type' => 'flat', 'rate_per_mile' => 4.32,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 32000, 'length_ft' => 53, 'pieces' => 20,
                'commodity_description' => 'Beverages and snack products',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Brenda Foster', 'shipper_phone' => '214-555-2323',
                'consignee_name' => 'Derek Long', 'consignee_phone' => '254-555-2424',
            ],
            [
                'load_number' => 'LB-2026-0013',
                'origin_name' => 'UPS Worldport',
                'origin_city' => 'Louisville', 'origin_state' => 'KY', 'origin_zip' => '40202',
                'origin_lat' => 38.2527, 'origin_lng' => -85.7585,
                'destination_name' => 'UPS Hub',
                'destination_city' => 'St. Louis', 'destination_state' => 'MO', 'destination_zip' => '63101',
                'destination_lat' => 38.6270, 'destination_lng' => -90.1994,
                'distance_miles' => 265, 'estimated_duration_minutes' => 240,
                'payout_amount' => 890.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.36,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 41000, 'length_ft' => 53, 'pieces' => 32,
                'commodity_description' => 'Express air containers - time-sensitive parcels',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => true, 'is_expedited' => true,
                'shipper_name' => 'Franklin Reed', 'shipper_phone' => '502-555-2525',
                'consignee_name' => 'Vanessa Cooper', 'consignee_phone' => '314-555-2626',
            ],
            [
                'load_number' => 'LB-2026-0014',
                'origin_name' => 'McKesson Medical',
                'origin_city' => 'Houston', 'origin_state' => 'TX', 'origin_zip' => '77027',
                'origin_lat' => 29.7388, 'origin_lng' => -95.4611,
                'destination_name' => 'Memorial Hermann Hospital',
                'destination_city' => 'Houston', 'destination_state' => 'TX', 'origin_zip' => '77030',
                'destination_lat' => 29.7078, 'destination_lng' => -95.3975,
                'distance_miles' => 8, 'estimated_duration_minutes' => 25,
                'payout_amount' => 185.00, 'payout_type' => 'flat', 'rate_per_mile' => 23.13,
                'load_type' => 'parcel', 'equipment_type' => 'van', 'weight_lbs' => 500, 'pieces' => 4,
                'commodity_description' => 'Pharmaceutical supplies - urgent hospital delivery',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => 36, 'temperature_max_f' => 46,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Dr. Priya Sharma', 'shipper_phone' => '713-555-2727',
                'consignee_name' => 'Nurse Rachel Adams', 'consignee_phone' => '713-555-2828',
            ],
            [
                'load_number' => 'LB-2026-0015',
                'origin_name' => 'Coca-Cola bottling',
                'origin_city' => 'Atlanta', 'origin_state' => 'GA', 'origin_zip' => '30318',
                'origin_lat' => 33.7905, 'origin_lng' => -84.4075,
                'destination_name' => 'Pepsi Distribution',
                'destination_city' => 'Birmingham', 'destination_state' => 'AL', 'origin_zip' => '35203',
                'destination_lat' => 33.5207, 'destination_lng' => -86.8025,
                'distance_miles' => 148, 'estimated_duration_minutes' => 135,
                'payout_amount' => 580.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.92,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 36000, 'length_ft' => 53, 'pieces' => 22,
                'commodity_description' => 'Beverages - full truckload soft drinks',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Monica Gray', 'shipper_phone' => '404-555-2929',
                'consignee_name' => 'Anthony Russell', 'consignee_phone' => '205-555-3030',
            ],
            [
                'load_number' => 'LB-2026-0016',
                'origin_name' => 'IKEA Distribution',
                'origin_city' => 'Savannah', 'origin_state' => 'GA', 'origin_zip' => '31401',
                'origin_lat' => 32.0809, 'origin_lng' => -81.0912,
                'destination_name' => 'IKEA Store',
                'destination_city' => 'Charlotte', 'destination_state' => 'NC', 'destination_zip' => '28202',
                'destination_lat' => 35.2271, 'destination_lng' => -80.8431,
                'distance_miles' => 254, 'estimated_duration_minutes' => 230,
                'payout_amount' => 950.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.74,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 30000, 'length_ft' => 53, 'pieces' => 15,
                'commodity_description' => 'Flat-pack furniture - knock-down boxes',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Ingrid Svensson', 'shipper_phone' => '912-555-3131',
                'consignee_name' => 'Marcus Bennett', 'consignee_phone' => '704-555-3232',
            ],
            [
                'load_number' => 'LB-2026-0017',
                'origin_name' => 'AutoZone Distribution',
                'origin_city' => 'Memphis', 'origin_state' => 'TN', 'origin_zip' => '38118',
                'origin_lat' => 35.0353, 'origin_lng' => -89.9767,
                'destination_name' => 'O\'Reilly Auto Parts',
                'destination_city' => 'Dallas', 'destination_state' => 'TX', 'destination_zip' => '75215',
                'destination_lat' => 32.7815, 'destination_lng' => -96.7680,
                'distance_miles' => 450, 'estimated_duration_minutes' => 400,
                'payout_amount' => 1350.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.00,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 38000, 'length_ft' => 53, 'pieces' => 34,
                'commodity_description' => 'Automotive parts and accessories',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Darren Phillips', 'shipper_phone' => '901-555-3333',
                'consignee_name' => 'Tanya Wright', 'consignee_phone' => '214-555-3434',
            ],
            [
                'load_number' => 'LB-2026-0018',
                'origin_name' => 'Cargill Meat Solutions',
                'origin_city' => 'Omaha', 'origin_state' => 'NE', 'origin_zip' => '68102',
                'origin_lat' => 41.2565, 'origin_lng' => -95.9345,
                'destination_name' => 'US Foods',
                'destination_city' => 'Kansas City', 'destination_state' => 'MO', 'destination_zip' => '64101',
                'destination_lat' => 39.0997, 'destination_lng' => -94.5786,
                'distance_miles' => 190, 'estimated_duration_minutes' => 170,
                'payout_amount' => 750.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.95,
                'load_type' => 'ftl', 'equipment_type' => 'reefer', 'weight_lbs' => 42000, 'length_ft' => 53, 'pieces' => 18,
                'commodity_description' => 'Frozen meat products - beef and pork',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => -5, 'temperature_max_f' => 5,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Jeffrey Olson', 'shipper_phone' => '402-555-3535',
                'consignee_name' => 'Stephanie Moore', 'consignee_phone' => '816-555-3636',
            ],
            [
                'load_number' => 'LB-2026-0019',
                'origin_name' => 'Tesla Gigafactory',
                'origin_city' => 'Austin', 'origin_state' => 'TX', 'origin_zip' => '78725',
                'origin_lat' => 30.2232, 'origin_lng' => -97.6167,
                'destination_name' => 'Tesla Service Center',
                'destination_city' => 'Dallas', 'destination_state' => 'TX', 'destination_zip' => '75207',
                'destination_lat' => 32.8020, 'destination_lng' => -96.8056,
                'distance_miles' => 195, 'estimated_duration_minutes' => 175,
                'payout_amount' => 680.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.49,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 18000, 'length_ft' => 53, 'pieces' => 8,
                'commodity_description' => 'EV battery components - delicate electronic parts',
                'is_hazmat' => true, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Amanda Torres', 'shipper_phone' => '512-555-3737',
                'consignee_name' => 'Brian Lee', 'consignee_phone' => '214-555-3838',
            ],
            [
                'load_number' => 'LB-2026-0020',
                'origin_name' => 'Whole Foods 365',
                'origin_city' => 'San Diego', 'origin_state' => 'CA', 'origin_zip' => '92101',
                'origin_lat' => 32.7157, 'origin_lng' => -117.1611,
                'destination_name' => 'Sprouts Farmers Market',
                'destination_city' => 'Los Angeles', 'destination_state' => 'CA', 'destination_zip' => '90012',
                'destination_lat' => 34.0522, 'destination_lng' => -118.2437,
                'distance_miles' => 120, 'estimated_duration_minutes' => 110,
                'payout_amount' => 520.00, 'payout_type' => 'flat', 'rate_per_mile' => 4.33,
                'load_type' => 'ftl', 'equipment_type' => 'reefer', 'weight_lbs' => 22000, 'length_ft' => 48, 'pieces' => 14,
                'commodity_description' => 'Organic produce - farm fresh vegetables',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => 34, 'temperature_max_f' => 40,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Laura Chen', 'shipper_phone' => '619-555-3939',
                'consignee_name' => 'Oscar Ramirez', 'consignee_phone' => '213-555-4040',
            ],
            [
                'load_number' => 'LB-2026-0021',
                'origin_name' => 'FedEx Freight',
                'origin_city' => 'Memphis', 'origin_state' => 'TN', 'origin_zip' => '38118',
                'origin_lat' => 35.0353, 'origin_lng' => -89.9767,
                'destination_name' => 'FedEx Freight',
                'destination_city' => 'Jacksonville', 'destination_state' => 'FL', 'destination_zip' => '32099',
                'destination_lat' => 30.3322, 'destination_lng' => -81.6557,
                'distance_miles' => 560, 'estimated_duration_minutes' => 500,
                'payout_amount' => 1680.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.00,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 45000, 'length_ft' => 53, 'pieces' => 28,
                'commodity_description' => 'LTL consolidation - mixed freight',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => false,
                'is_team_load' => true, 'is_expedited' => false,
                'shipper_name' => 'Calvin Barnes', 'shipper_phone' => '901-555-4141',
                'consignee_name' => 'Megan Price', 'consignee_phone' => '904-555-4242',
            ],
            [
                'load_number' => 'LB-2026-0022',
                'origin_name' => 'Buc-ee\'s Distribution',
                'origin_city' => 'Houston', 'origin_state' => 'TX', 'origin_zip' => '77060',
                'origin_lat' => 29.9012, 'origin_lng' => -95.4567,
                'destination_name' => 'Buc-ee\'s Travel Center',
                'destination_city' => 'San Marcos', 'destination_state' => 'TX', 'destination_zip' => '78666',
                'destination_lat' => 29.8833, 'destination_lng' => -97.9414,
                'distance_miles' => 165, 'estimated_duration_minutes' => 150,
                'payout_amount' => 620.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.76,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 28000, 'length_ft' => 53, 'pieces' => 20,
                'commodity_description' => 'Convenience store merchandise - snacks and supplies',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Beau Thompson', 'shipper_phone' => '713-555-4343',
                'consignee_name' => 'Crystal Nelson', 'consignee_phone' => '512-555-4444',
            ],
            [
                'load_number' => 'LB-2026-0023',
                'origin_name' => 'Walmart FC',
                'origin_city' => 'Bentonville', 'origin_state' => 'AR', 'origin_zip' => '72712',
                'origin_lat' => 36.3722, 'origin_lng' => -94.2088,
                'destination_name' => 'Sam\'s Club DC',
                'destination_city' => 'Dallas', 'destination_state' => 'TX', 'destination_zip' => '75247',
                'destination_lat' => 32.9137, 'destination_lng' => -96.8903,
                'distance_miles' => 395, 'estimated_duration_minutes' => 360,
                'payout_amount' => 1280.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.24,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 42000, 'length_ft' => 53, 'pieces' => 30,
                'commodity_description' => 'General merchandise - Sam\'s Club restock',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => false, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Danny Miller', 'shipper_phone' => '479-555-4545',
                'consignee_name' => 'Tammy Wilson', 'consignee_phone' => '214-555-4646',
            ],
            [
                'load_number' => 'LB-2026-0024',
                'origin_name' => 'McKesson DC',
                'origin_city' => 'Memphis', 'origin_state' => 'TN', 'origin_zip' => '38118',
                'origin_lat' => 35.0353, 'origin_lng' => -89.9767,
                'destination_name' => 'Baptist Memorial Hospital',
                'destination_city' => 'Jackson', 'destination_state' => 'MS', 'destination_zip' => '39201',
                'destination_lat' => 32.2988, 'destination_lng' => -90.1848,
                'distance_miles' => 210, 'estimated_duration_minutes' => 190,
                'payout_amount' => 720.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.43,
                'load_type' => 'ftl', 'equipment_type' => 'reefer', 'weight_lbs' => 18000, 'length_ft' => 48, 'pieces' => 10,
                'commodity_description' => 'Pharmaceutical supplies - temperature-sensitive medications',
                'is_hazmat' => false, 'is_temperature_controlled' => true,
                'temperature_min_f' => 36, 'temperature_max_f' => 46,
                'requires_liftgate' => true, 'requires_pallet_jack' => false,
                'is_team_load' => false, 'is_expedited' => true,
                'shipper_name' => 'Dr. Angela Foster', 'shipper_phone' => '901-555-4747',
                'consignee_name' => 'Nurse James Carter', 'consignee_phone' => '601-555-4848',
            ],
            [
                'load_number' => 'LB-2026-0025',
                'origin_name' => 'Dollar General DC',
                'origin_city' => 'Indianapolis', 'origin_state' => 'IN', 'origin_zip' => '46231',
                'origin_lat' => 39.7684, 'origin_lng' => -86.1581,
                'destination_name' => 'Dollar General Store',
                'destination_city' => 'Nashville', 'destination_state' => 'TN', 'destination_zip' => '37201',
                'destination_lat' => 36.1627, 'destination_lng' => -86.7816,
                'distance_miles' => 285, 'estimated_duration_minutes' => 260,
                'payout_amount' => 920.00, 'payout_type' => 'flat', 'rate_per_mile' => 3.23,
                'load_type' => 'ftl', 'equipment_type' => 'van', 'weight_lbs' => 40000, 'length_ft' => 53, 'pieces' => 26,
                'commodity_description' => 'Dollar store merchandise - mixed retail goods',
                'is_hazmat' => false, 'is_temperature_controlled' => false,
                'requires_liftgate' => true, 'requires_pallet_jack' => true,
                'is_team_load' => false, 'is_expedited' => false,
                'shipper_name' => 'Nathan Scott', 'shipper_phone' => '317-555-4949',
                'consignee_name' => 'Heather Young', 'consignee_phone' => '615-555-5050',
            ],
        ];

        foreach ($loads as $data) {
            $data['provider'] = 'internal';
            $data['status'] = 'available';
            UrbanGoodzLoadBoardLoad::create($data);
        }
    }
}
