@extends('layouts.admin.app')

@section('title', translate('AI Chief of Staff Briefs'))

@section('content')
    <div class="content container-fluid">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div>
                <h1 class="page-header-title">{{ translate('AI Chief of Staff Briefs') }}</h1>
                <p class="text-muted">{{ translate('View role-specific alerts, plans, and business needs generated by the Chief of Staff agent.') }}</p>
            </div>
            <a href="{{ route('admin.urban-goodz.ai-operations.workforce.index') }}" class="btn btn-outline--primary">
                <i class="tio-arrow-back"></i> {{ translate('Back to Workforce') }}
            </a>
        </div>

        <div class="row g-3 mb-4">
            <div class="col-12">
                <div class="card card-body">
                    <form method="GET" action="{{ route('admin.urban-goodz.ai-operations.workforce.briefs') }}" class="row g-3 align-items-center">
                        <div class="col-md-4">
                            <label class="form-label font-weight-bold">{{ translate('Select Brief Role') }}</label>
                            <select name="role" class="form-control" onchange="this.form.submit()">
                                <option value="Executive" {{ $selectedRole === 'Executive' ? 'selected' : '' }}>{{ translate('Executive Daily Brief') }}</option>
                                <option value="Owner" {{ $selectedRole === 'Owner' ? 'selected' : '' }}>{{ translate('Owner') }}</option>
                                <option value="Admin" {{ $selectedRole === 'Admin' ? 'selected' : '' }}>{{ translate('Admin') }}</option>
                                <option value="Dispatcher" {{ $selectedRole === 'Dispatcher' ? 'selected' : '' }}>{{ translate('Dispatcher') }}</option>
                                <option value="Vendor Support" {{ $selectedRole === 'Vendor Support' ? 'selected' : '' }}>{{ translate('Vendor Support') }}</option>
                                <option value="Customer Support" {{ $selectedRole === 'Customer Support' ? 'selected' : '' }}>{{ translate('Customer Support') }}</option>
                                <option value="Finance" {{ $selectedRole === 'Finance' ? 'selected' : '' }}>{{ translate('Finance') }}</option>
                                <option value="Business Operations" {{ $selectedRole === 'Business Operations' ? 'selected' : '' }}>{{ translate('Business Operations') }}</option>
                            </select>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header bg-light">
                <div class="d-flex justify-content-between align-items-center">
                    <h3 class="card-title mb-0">{{ translate($brief['title'] ?? ($selectedRole . ' Brief')) }}</h3>
                    <span class="badge badge-soft-dark">{{ $brief['date'] ?? today()->toDateString() }}</span>
                </div>
            </div>
            <div class="card-body">
                @if($selectedRole === 'Executive')
                    <div class="row g-3 mb-4">
                        <div class="col-md-3">
                            <div class="card bg-light p-3 text-center">
                                <h4 class="text-muted mb-1">{{ translate('Completed Tasks') }}</h4>
                                <h3>{{ $brief['metrics']['completed'] ?? 0 }}</h3>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-light p-3 text-center">
                                <h4 class="text-muted mb-1">{{ translate('In Progress') }}</h4>
                                <h3>{{ $brief['metrics']['in_progress'] ?? 0 }}</h3>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-light p-3 text-center">
                                <h4 class="text-muted mb-1">{{ translate('Active Needs') }}</h4>
                                <h3>{{ $brief['metrics']['business_needs'] ?? 0 }}</h3>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="card bg-light p-3 text-center">
                                <h4 class="text-muted mb-1">{{ translate('Human Actions') }}</h4>
                                <h3>{{ $brief['metrics']['human_actions_required'] ?? 0 }}</h3>
                            </div>
                        </div>
                    </div>

                    <div class="mb-4">
                        <h4>{{ translate('Business Needs requiring Immediate Attention') }}</h4>
                        <ul class="list-group">
                            @forelse($brief['business_needs'] ?? [] as $need)
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        <strong>{{ $need->title }}</strong>
                                        <div class="text-muted small">{{ $need->description }}</div>
                                    </div>
                                    <span class="badge badge-soft-danger">{{ $need->severity }}</span>
                                </li>
                            @empty
                                <li class="list-group-item text-muted">{{ translate('No critical business needs detected.') }}</li>
                            @endforelse
                        </ul>
                    </div>

                    <div>
                        <h4>{{ translate('Urgent Human Action Items') }}</h4>
                        <ul class="list-group">
                            @forelse($brief['urgent_actions'] ?? [] as $action)
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        <strong>{{ $action->title }}</strong>
                                        <div class="text-muted small">{{ $action->description }}</div>
                                        <div class="text-info mt-1 small">{{ translate('Assigned Role:') }} <strong>{{ $action->assigned_role }}</strong></div>
                                    </div>
                                    <span class="badge badge-soft-warning">{{ $action->priority }}</span>
                                </li>
                            @empty
                                <li class="list-group-item text-muted">{{ translate('No urgent human actions required.') }}</li>
                            @endforelse
                        </ul>
                    </div>
                @else
                    <div class="mb-4">
                        <h4>{{ translate('Pending Actions for ') }} {{ $selectedRole }}</h4>
                        <ul class="list-group">
                            @forelse($brief['actions_required'] ?? [] as $action)
                                <li class="list-group-item">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <strong>{{ $action->title }}</strong>
                                        <span class="badge badge-soft-warning">{{ $action->priority }}</span>
                                    </div>
                                    <div class="text-muted small mt-1">{{ $action->description }}</div>
                                    @if($action->recommended_next_step)
                                        <div class="text-info mt-2 small">
                                            <strong>{{ translate('Recommended Next Step:') }}</strong> {{ $action->recommended_next_step }}
                                        </div>
                                    @endif
                                </li>
                            @empty
                                <li class="list-group-item text-muted">{{ translate('No pending actions assigned to this role.') }}</li>
                            @endforelse
                        </ul>
                    </div>

                    <div>
                        <h4>{{ translate('Active Business Needs') }}</h4>
                        <ul class="list-group">
                            @forelse($brief['business_needs'] ?? [] as $need)
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div>
                                        <strong>{{ $need->title }}</strong>
                                        <div class="text-muted small">{{ $need->description }}</div>
                                    </div>
                                    <span class="badge badge-soft-info">{{ $need->severity }}</span>
                                </li>
                            @empty
                                <li class="list-group-item text-muted">{{ translate('No business needs currently matching this role.') }}</li>
                            @endforelse
                        </ul>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection
