<?php

return [
    'capability_map' => [
        'control-center' => [
            'key' => 'control-center',
            'route' => 'admin.urban-goodz.index',
            'label' => 'Control Center',
            'icon' => 'tio-dashboard-outlined',
            'group' => 'core',
            'description' => 'Urban Goodz platform dashboard and overview',
            'module_permission' => 'urban_goodz_platform_core',
            'availability_status' => 'active',
        ],
        'business-types' => [
            'key' => 'business-types',
            'route' => 'admin.urban-goodz.business-types.index',
            'label' => 'Business Types',
            'icon' => 'tio-category',
            'group' => 'core',
            'description' => 'Urban Goodz business type definitions and mapping',
            'module_permission' => 'urban_goodz_business_types',
            'availability_status' => 'active',
        ],
        'capabilities' => [
            'key' => 'capabilities',
            'route' => 'admin.urban-goodz.capabilities.index',
            'label' => 'Capabilities',
            'icon' => 'tio-slider',
            'group' => 'core',
            'description' => 'Feature capabilities per business type',
            'module_permission' => 'urban_goodz_capabilities',
            'availability_status' => 'active',
        ],
        'order-anywhere' => [
            'key' => 'order-anywhere',
            'route' => 'admin.urban-goodz.order-anywhere.index',
            'label' => 'Order Anywhere',
            'icon' => 'tio-shopping-cart',
            'group' => 'commerce',
            'description' => 'Manage Order Anywhere requests across all business types',
            'module_permission' => 'urban_goodz_order_anywhere',
            'availability_status' => 'active',
        ],
        'payments' => [
            'key' => 'payments',
            'route' => 'admin.urban-goodz.payments.index',
            'label' => 'Payment Center',
            'icon' => 'tio-money',
            'group' => 'core',
            'description' => 'Payment ledgers, splits, and staged_test mode',
            'module_permission' => 'urban_goodz_payments',
            'availability_status' => 'active',
        ],
        'fashion-fit' => [
            'key' => 'fashion-fit',
            'route' => 'admin.urban-goodz.fashion-fit.index',
            'label' => 'Fashion Fit',
            'icon' => 'tio-tshirt',
            'group' => 'services',
            'description' => 'Measurement requests and tailoring services',
            'module_permission' => 'urban_goodz_fashion_fit',
            'availability_status' => 'active',
        ],
        'stylist-requests' => [
            'key' => 'stylist-requests',
            'route' => 'admin.stylist-request.list',
            'label' => 'Stylist Requests',
            'icon' => 'tio-tshirt',
            'group' => 'services',
            'description' => 'Fashion stylist request management',
            'module_permission' => 'urban_goodz_stylist_requests',
            'availability_status' => 'active',
        ],
        'ai-concierge' => [
            'key' => 'ai-concierge',
            'route' => 'admin.urban-goodz.ai-concierge.intents',
            'label' => 'AI Concierge',
            'icon' => 'tio-robot',
            'group' => 'ai',
            'description' => 'AI customer query, intent management, and conversation review',
            'module_permission' => 'urban_goodz_ai_concierge',
            'availability_status' => 'active',
        ],
        'file-library' => [
            'key' => 'file-library',
            'route' => 'admin.urban-goodz.files.index',
            'label' => 'File Library',
            'icon' => 'tio-folder-open',
            'group' => 'core',
            'description' => 'All uploaded files across Urban Goodz features',
            'module_permission' => 'urban_goodz_file_library',
            'availability_status' => 'active',
        ],
        'book-anything' => [
            'key' => 'book-anything',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'book-anything'],
            'label' => 'Book Anything',
            'icon' => 'tio-calendar',
            'group' => 'services',
            'description' => 'Service bookings and appointments',
            'module_permission' => 'urban_goodz_book_anything',
            'availability_status' => 'active',
        ],
        'creator-commerce' => [
            'key' => 'creator-commerce',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'creator-commerce'],
            'label' => 'Creator Commerce',
            'icon' => 'tio-star',
            'group' => 'social',
            'description' => 'Creator merchandise, commerce, and commissions',
            'module_permission' => 'urban_goodz_creator_commerce',
            'availability_status' => 'active',
        ],
        'community' => [
            'key' => 'community',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'community'],
            'label' => 'Community Marketplace',
            'icon' => 'tio-users',
            'group' => 'social',
            'description' => 'Community posts, marketplace items, and comments',
            'module_permission' => 'urban_goodz_community',
            'availability_status' => 'active',
        ],
        'earn-money' => [
            'key' => 'earn-money',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'earn-money'],
            'label' => 'Earn Money',
            'icon' => 'tio-money',
            'group' => 'monetization',
            'description' => 'Affiliate and referral program management',
            'module_permission' => 'urban_goodz_earn_money',
            'availability_status' => 'active',
        ],
        'logistics' => [
            'key' => 'logistics',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'logistics'],
            'label' => 'Logistics',
            'icon' => 'tio-truck',
            'group' => 'logistics',
            'description' => 'Freight and logistics load management',
            'module_permission' => 'urban_goodz_logistics',
            'availability_status' => 'active',
        ],
        'medical-courier' => [
            'key' => 'medical-courier',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'medical-courier'],
            'label' => 'Medical Courier',
            'icon' => 'tio-medical',
            'group' => 'logistics',
            'description' => 'Medical specimen transport and custody tracking',
            'module_permission' => 'urban_goodz_medical_courier',
            'availability_status' => 'active',
        ],
        'events' => [
            'key' => 'events',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'events'],
            'label' => 'Events',
            'icon' => 'tio-calendar',
            'group' => 'marketing',
            'description' => 'Event management and ticketing',
            'module_permission' => 'urban_goodz_events',
            'availability_status' => 'active',
        ],
        'rentals' => [
            'key' => 'rentals',
            'route' => 'admin.urban-goodz.section',
            'route_params' => ['section' => 'rentals'],
            'label' => 'Rentals',
            'icon' => 'tio-car',
            'group' => 'fulfillment',
            'description' => 'Vehicle, car, and equipment rentals',
            'module_permission' => 'urban_goodz_rentals',
            'availability_status' => 'backend_controlled',
        ],
        'vehicle-rentals' => [
            'key' => 'vehicle-rentals',
            'route' => 'admin.urban-goodz.section',
            'route_params' => ['section' => 'vehicle-rentals'],
            'label' => 'Vehicle Rentals',
            'icon' => 'tio-car',
            'group' => 'fulfillment',
            'description' => 'Car, motorcycle, and vehicle fleet rentals',
            'module_permission' => 'urban_goodz_rentals',
            'availability_status' => 'backend_controlled',
        ],
        'plus' => [
            'key' => 'plus',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'plus'],
            'label' => 'Urban Goodz+',
            'icon' => 'tio-crown',
            'group' => 'subscription',
            'description' => 'Premium subscription and membership management',
            'module_permission' => 'urban_goodz_plus',
            'availability_status' => 'active',
        ],
        'spotlight' => [
            'key' => 'spotlight',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'spotlight'],
            'label' => 'Black-Owned Spotlight',
            'icon' => 'tio-star',
            'group' => 'marketing',
            'description' => 'Black-owned business promotions and spotlight features',
            'module_permission' => 'urban_goodz_spotlight',
            'availability_status' => 'active',
        ],
        'discovery' => [
            'key' => 'discovery',
            'route' => 'admin.urban-goodz.modules.index',
            'route_params' => ['section' => 'discovery'],
            'label' => 'Discovery',
            'icon' => 'tio-search',
            'group' => 'ai',
            'description' => 'Search analytics, demand signals, and trend discovery',
            'module_permission' => 'urban_goodz_discovery',
            'availability_status' => 'active',
        ],
    ],

    'groups' => [
        'core' => ['label' => 'Core Platform', 'sort_order' => 0],
        'commerce' => ['label' => 'Commerce', 'sort_order' => 1],
        'services' => ['label' => 'Services', 'sort_order' => 2],
        'fulfillment' => ['label' => 'Rentals', 'sort_order' => 3],
        'social' => ['label' => 'Social / Creator', 'sort_order' => 4],
        'logistics' => ['label' => 'Delivery / Driver', 'sort_order' => 5],
        'ai' => ['label' => 'AI Services', 'sort_order' => 6],
        'marketing' => ['label' => 'Marketing / Subscription', 'sort_order' => 7],
        'monetization' => ['label' => 'Monetization', 'sort_order' => 8],
        'subscription' => ['label' => 'Subscription', 'sort_order' => 9],
    ],

    'business_type_map' => [
        'restaurant' => ['fulfillment' => ['order-anywhere', 'menu-management']],
        'food_truck' => ['fulfillment' => ['order-anywhere', 'menu-management']],
        'grocery_market' => ['fulfillment' => ['order-anywhere', 'product-inventory']],
        'retail_shopping' => ['fulfillment' => ['order-anywhere', 'product-inventory']],
        'beauty_supply_hair_provider' => ['fulfillment' => ['order-anywhere', 'product-inventory'], 'services' => ['appointment-booking']],
        'service_provider' => ['services' => ['book-anything', 'appointment-booking']],
        'rental_provider' => ['fulfillment' => ['rental-inventory', 'rental-calendar', 'daily-rate-management', 'hourly-rate-management', 'deposit-management', 'renter-verification', 'pickup-return-management', 'damage-report-management']],
        'car_rental' => ['fulfillment' => ['vehicle-inventory', 'rental-calendar', 'daily-rate-management', 'deposit-management', 'renter-verification', 'pickup-return-management', 'damage-report-management']],
        'vehicle_rental' => ['fulfillment' => ['vehicle-inventory', 'rental-calendar', 'daily-rate-management', 'hourly-rate-management', 'deposit-management', 'renter-verification', 'pickup-return-management', 'damage-report-management']],
        'equipment_rental' => ['fulfillment' => ['rental-inventory', 'rental-calendar', 'daily-rate-management', 'deposit-management', 'pickup-return-management', 'damage-report-management']],
        'event_vendor' => ['social' => ['events', 'community-marketplace'], 'core' => ['payment-splits']],
        'courier' => ['logistics' => ['logistics', 'local-delivery', 'driver-dispatch']],
        'medical_courier' => ['logistics' => ['medical-courier', 'driver-dispatch']],
        'creator' => ['content' => ['creator-commerce'], 'social' => ['community-marketplace', 'events']],
        'fashion_fit_provider' => ['fashion' => ['fashion-fit'], 'ai' => ['ai-concierge'], 'services' => ['book-anything', 'appointment-booking']],
    ],
];
